# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: ["QuantumRNG/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["QuantumRNG/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # The default settings with a working directory
    defaults:
      run:
        working-directory: QuantumRNG
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checkout code
      - name: 'Checkout code'
        uses: actions/checkout@main

        # Build the Quantum Component
      - name: 'Build the Quantum Component'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_QUANTUM_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release --output ./output
          popd

        # Estimate Quantum Resources
      - name: 'Estimate Quantum Resources'
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_QUANTUM_ESTIMATION_PACKAGE_PATH }}'
          dotnet test --verbosity normal
          popd
